name: hashicorp/hashicat-aws/infrastructure-tests
on:
  workflow_dispatch: 
  push:
    branches:
      - 'master'
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Terraform Validate
        run: |-
          terraform init
          terraform validate
permissions:
  contents: read