name: Build, Push, and Deploy Gooloom-CGV Spring Boot App (WAS)

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # 어느 디렉토리에서 커맨드를 실행할 지 결정
      working-directory: ./gooloom-was
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 19  # Change this to your desired Java version
        distribution: 'temurin'
        
    - name: Set Date as Image Tag
      id: set_tag
      run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Build Docker image
      run:
        docker buildx build --platform=linux/amd64 -t csm4903/gooloom-was:$IMAGE_TAG .
      working-directory: ${{ env.working-directory }}

    - name: Log in to Docker Hub
      run: |
        docker login -u csm4903 -p ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push Docker image to Docker Hub
      run: |
        docker tag gooloom-was csm4903/gooloom-was:latest
        docker push csm4903/gooloom-was:latest
